version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: company_manual_project_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d
    networks:
      - springboot-postgres-network

volumes:
  postgres-data:

networks:
  springboot-postgres-network:
