-- INSERT INTO articles (public_id, description, title, content, version, status, edited_by, is_editable)
-- VALUES
--     ('101', 'Description Approved - 101 - version 1', 'Titel Approved - 101 - version 1', 'Inhalt des Artikels - Approved - 101 - version 1', 1, 'APPROVED', 'user', false),
--     ('101', 'Description Approved - 101 - version 2', 'Titel Approved - 101 - version 2', 'Inhalt des Artikels - Approved - 101 - version 2', 2, 'APPROVED', 'user', true)
